name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build # Will be used down for docker image building
          path: |
            target/**
  docker_build:

    runs-on: ubuntu-latest
    needs: build

    env:
      REGISTRY_REPO: abdellbou/cicd_semsar
    steps:
      - uses: actions/checkout@v3
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build # Artifact name
          path: target
      - name: Build image
        run: docker image build -t $REGISTRY_REPO:latest --file Dockerfile .

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to registery
        run: docker push $REGISTRY_REPO:latest

      - name: Deploy Docker Image to Heroku

        uses: techmmunity/docker-heroku-deploy@v1.0.0
        with:
          # Email Linked to your Heroku Account
          email: ${{secrets.HEROKU_EMAIL}}
          # Your Heroku API Key
          api_key: ${{secrets.HEROKU_API_KEY}}
          # Your Heroku App Name
          app_name: ${{secrets.HEROKU_APP}}